name: Deploy to EC2
on: 
    #trigger deployment only to master branch
  push:
    branches:
      - master
jobs:
  build: 
    strategy:
      matrix:
        operating-system: [ ubuntu-latest ]
        node-version: [ 20.x ]
    runs-on: ${{  matrix.operating-system  }}
    steps: 
      - name: checkout the code
        uses: actions/checkout@v4
      - name: install nodeJS 
        uses: actions/setup-node@v4
        with: 
          node-version: ${{  matrix.node-version  }}
          cache: 'npm'
      - name: install dependencies
        run: npm ci
      - name: Build code
        run: npm run build --if-present
    # deploy job to server
      - name: Deploy to server
        uses:  easingthemes/ssh-deploy@v5.0.3
        with:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          REMOTE_HOST:  ${{ secrets.HOST_DNS }}
          REMOTE_USER: ${{ secrets.USERNAME }}
          TARGET: ${{ secrets.TARGET_DIR }}
      - name: Executing ssh commands using ssh key
        uses: appleboy/ssh-action@master
        with:
           host: ${{ secrets.HOST_DNS  }}
           username: ${{ secrets.USERNAME }}
           key: ${{ secrets.EC2_SSH_KEY }}
           script: |
             sudo apt-get update
             cd home
             npm install
             npm build